layout_spectrum: 0.009241974214091897
typography_spectrum: 0.7142920354381204
color:
  brandStrength: 0.4560567068401724
  lightness: 0.8625325560569763
  saturation: 0.3305984800681472
  rhythmicContrast: 0.8998410883359611
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
name: ' Sustainability Review '
navigation:
  - name: CV
    url: 'http://www.mawle.com'
    type: external
  - name: Twitter
    url: 'https://twitter.com/RichardMawle'
    type: external
  - name: LinkedIn
    url: 'https://uk.linkedin.com/in/richardmawle'
    type: external
  - name: Work
    url: 'http://people.uwe.ac.uk/Pages/person.aspx?accountname=CAMPUS%5Cr-mawle'
    type: external
